#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <functional>
#include <signal.h>
#include <time.h>
#include <sys/mman.h>
#include <vector>
#include <iostream>
#include <thread>
#include <cstring>
#include <inttypes.h>
#include <blend2d.h>